### ISSUE TITLE
Select List is kind of very high

### ISSUE THREAD

**Issue by benthebear** [palasthotel/blockX#12]
@EdwardBock When using a Select-Widget, the height is … quite … high …

<img width="321" alt="Bildschirmfoto 2021-03-30 um 10 06 10" src="https://user-images.githubusercontent.com/49137/112955375-a446c280-913f-11eb-854b-a0ab3fc2b8c4.png">

**Comment by benthebear** [comment]
To been seen in the wild in the UA-Project in this path … `/wp-admin/post.php?post=7149&action=edit&lang=de`

**Comment by EdwardBock** [comment]
Was a false positive that had it's origin in a other plugins warning.
