### ISSUE TITLE
Pre-Rendering Hook

### ISSUE THREAD

**Issue by benthebear** [palasthotel/blockX#14]
@EdwardBock Please, add a hook that allows for pre-rendering manipulation of the content of the block. Ideal would be, if the hooks gets the whole `$content` so you can compare several Widgets with each other. For something like …

>  If `$content->title` is empty but  `$content->category` is set, then take the title of the category as value of the title.

**Comment by EdwardBock** [comment]
There are two more filters with version 1.0.8.

Have a look at the updated [README.md](https://github.com/palasthotel/blockX#filters)
