### ISSUE TITLE
Block breaks, when Special Characters are added to Textarea

### ISSUE THREAD

**Issue by benthebear** [palasthotel/blockX#15]
Dear @EdwardBock When having a Block with a Text-Field of Textarea-Type, with an text containing a €-Sign, the Block breaks … :D

Reproduction: UA, add "Free Teaser"-Block. Type Text with € in the "Teaser-Text"-Textarea and the hit "Änderungen übernehmen" you'll get this …

<img width="620" alt="Bildschirmfoto 2021-03-30 um 16 57 25" src="https://user-images.githubusercontent.com/49137/113010357-0ec82480-9179-11eb-98dd-687c9beb1f75.png">

**Comment by benthebear** [comment]
If you remove the € Character via the Code-Editor, it works agains.

**Comment by EdwardBock** [comment]
ok, let's check. That would be a weird special char.

**Comment by benthebear** [comment]
It's a common € Sign hihi.

**Comment by EdwardBock** [comment]
The btoa hash does not like utf-8 chars. So we first have to escape and url encode stringified object before we can hash it. That only affects the SSRQueue implementation of blockx so no data is broken and everything should be fine after plugin update.

Fix comes with version 1.0.9
