### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by JanaME** [palasthotel/blockX#16]
Hey @EdwardBock 

sometimes I get the message

<img width="746" alt="Bildschirmfoto 2021-04-16 um 11 09 38" src="https://user-images.githubusercontent.com/4892599/115002995-a336c480-9ea5-11eb-89f3-b730972f025f.png">

(Version 1.0.10)

It is possible to simply reactivate the plugin without errors and I couldn’t find out yet, what the problem is, but maybe you have an idea?

**Comment by EdwardBock** [comment]
Should be fixed. I guess :D
