### ISSUE TITLE
Widget TaxQuery: Simplify return value?

### ISSUE THREAD

**Issue by greatestview** [palasthotel/blockX#20]
Hey @EdwardBock,

currently when implementing a `Palasthotel\WordPress\BlockX\Widgets\TaxQuery` widget you have to do some transformation, e. g. like this:

```php
public function prepare(\stdClass $content): \stdClass
{
	$content = parent::prepare($content);
	// build wp tax_query with data provided by $content->tax_query
	$tax_query = [];
	if (isset($content->tax_query["taxonomies"])) {
		if (
			count($content->tax_query["taxonomies"]) > 1
			&& isset($content->tax_query["relation"])
		) {
			$tax_query["relation"] = $content->tax_query["relation"];
		}
		foreach ($content->tax_query["taxonomies"] as $taxonomy) {
			$query_tax_array = [
				"taxonomy" => $taxonomy["taxonomy"],
				"terms"    => $taxonomy["termIds"],
			];
			if (isset($taxonomy["operator"])) {
				$query_tax_array["operator"] = $taxonomy["operator"];
			}
			$tax_query[] = $query_tax_array;
		}
	}
	$theQuery = new \WP_Query([
		"post_type" => "post",
		"posts_per_page" => 1,
		"tax_query" => $tax_query,
	]);

	// … continue with $theQuery and inject data into $content
}
```

That is necessary, because naming issues and this part in the [WP_Query Reference](https://developer.wordpress.org/reference/classes/wp_query/) regarding the `tax_query` argument:

> - **tax_query** (*array*) – use taxonomy parameters (available since version 3.1).
>   - **relation** (*string*) – The logical relationship between each inner taxonomy array when there is more than one. Possible values are ‘AND’, ‘OR’. **Do not use with a single inner taxonomy array.**

I would like to skip the entire transforming part and pass the TaxQuery data directly into WP_Query, so that the transformation part moves into the TaxQuery widget. Like this:

```php
public function prepare(\stdClass $content): \stdClass
{
	$content = parent::prepare($content);
	$theQuery = new \WP_Query([
		"post_type" => "post",
		"posts_per_page" => 1,
		"tax_query" => $content->tax_query,
	]);

	// … continue with $theQuery and inject data into $content
}
```

This would make it much easier to work with that widget and keep the code nice and clean. What do you think?

**Comment by EdwardBock** [comment]
I see your point. There is a utility function that could and should be public somewhere that is right now private.

https://github.com/palasthotel/blockX/blob/master/public/classes/Blocks/Posts.php#L92-L136

But perhaps it would be even easier if the content structure args and WP_Query args would be compatible. I just try to remember why I didn't do that in the first place 🤔

**Comment by EdwardBock** [comment]
@greatestview with Version 1.1.4 there is now a new static function on the TaxQuery Widget class that helps tranfoming the widgets arguments structure to wp taxonomy query args. 

- Static helper function https://github.com/palasthotel/blockX/blob/5b5d9769d03db84d7d6b5f36cb0dc1687ecad63a/public/classes/Widgets/TaxQuery.php#L67-L102
- Example usage https://github.com/palasthotel/blockX/blob/5b5d9769d03db84d7d6b5f36cb0dc1687ecad63a/public/classes/Blocks/Posts.php#L80-L82

**Comment by greatestview** [comment]
Hooray!
